fixtures:
  forge_modules:
    stdlib: 'puppetlabs-stdlib'
    concat: 'puppetlabs-concat'
  repositories:
    # litmus dependencies
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'git://github.com/puppetlabs/provision.git'
  symlinks:
    bind: "#{source_dir}"
