---
.travis.yml:
  acceptance:
    - '*'
  includes:
    -
      bundler_args:
      env: PLATFORMS=centos6
      rvm: 2.5.3
      before_script:
        - bundle exec rake 'litmus:provision[docker, waffleimage/centos6]'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args:
      env: PLATFORMS=centos7
      rvm: 2.5.3
      before_script:
        - bundle exec rake 'litmus:provision[docker, waffleimage/centos7]'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args:
      env: PLATFORMS=debian8
      before_script:
        - bundle exec rake 'litmus:provision[docker, waffleimage/debian8]'
        - bundle exec bolt command run 'apt-get install lsb-release gnupg iproute2 -y' --inventoryfile inventory.yaml --targets='localhost*'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args:
      env: PLATFORMS=debian9
      before_script:
        - bundle exec rake 'litmus:provision[docker, waffleimage/debian9]'
        - bundle exec bolt command run 'apt-get install lsb-release gnupg iproute2 -y' --inventoryfile inventory.yaml --targets='localhost*'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args:
      env: PLATFORMS=ubuntu16.04
      before_script:
        - bundle exec rake 'litmus:provision[docker, waffleimage/ubuntu16.04]'
        - bundle exec bolt command run 'apt-get install lsb-release gnupg iproute2 -y' --inventoryfile inventory.yaml --targets='localhost*'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args:
      env: PLATFORMS=ubuntu18.04
      before_script:
        - bundle exec rake 'litmus:provision[docker, waffleimage/ubuntu18.04]'
        - bundle exec bolt command run 'apt-get install lsb-release gnupg iproute2 -y' --inventoryfile inventory.yaml --targets='localhost*'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      stage: acceptance
      sudo: required
  allow_failures:
    -
      bundler_args:
      env: PLATFORMS=centos7
      rvm: 2.5.3
      before_script:
        - bundle exec rake 'litmus:provision[docker, waffleimage/centos7]'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      stage: acceptance
      sudo: required
  user: camptocamp
  secure: "HLOnMqlB03FRSusdbWf/afjyc0jbHgoVZ/HF4x8y9H7g8utuBQJxjsAAxdrAme5JOuN6i3+J1A8IrpcRIwicBDk/yav4IrT65fCyzfBz7p6Kx2doT4a3WwiMXzqgcDe8Z8l7hu531HnXzxXEjCKCoEFiUBWI+4ULXQk3ATMrm/U="
  branches:
    - master
    - /^\d/
  deploy_to_forge:
    enabled: true
    tag_regex: "^\\d"
Gemfile:
  required:
    ':system_tests':
      - gem: beaker-hostgenerator
      - gem: "puppet-module-posix-system-r#{minor_version}"
  optional:
    ':development':
      - gem: 'github_changelog_generator'
Rakefile:
  changelog_version_tag_pattern: '%s'
