---
.travis.yml:
  acceptance:
    - '*'
  includes:
    - rvm: default
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet5
        - BEAKER_debug=true
        - BEAKER_setfile=debian8-64{hypervisor=docker}
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
      stage: acceptance
    - rvm: default
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet5
        - BEAKER_debug=true
        - BEAKER_setfile=debian9-64{hypervisor=docker}
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
      stage: acceptance
    - rvm: default
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet5
        - BEAKER_debug=true
        - BEAKER_setfile=ubuntu1404-64{hypervisor=docker}
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
      stage: acceptance
    - rvm: default
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet5
        - BEAKER_debug=true
        - BEAKER_setfile=ubuntu1604-64{hypervisor=docker}
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
      stage: acceptance
    - rvm: default
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet5
        - BEAKER_debug=true
        - BEAKER_setfile=ubuntu1804-64{hypervisor=docker}
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
    - rvm: default
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet5
        - BEAKER_debug=true
        - BEAKER_setfile=centos6-64{hypervisor=docker}
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
      stage: acceptance
    - rvm: default
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet5
        - BEAKER_debug=true
        - BEAKER_setfile=centos7-64{hypervisor=docker}
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
      stage: acceptance
  user: camptocamp
  secure: "HLOnMqlB03FRSusdbWf/afjyc0jbHgoVZ/HF4x8y9H7g8utuBQJxjsAAxdrAme5JOuN6i3+J1A8IrpcRIwicBDk/yav4IrT65fCyzfBz7p6Kx2doT4a3WwiMXzqgcDe8Z8l7hu531HnXzxXEjCKCoEFiUBWI+4ULXQk3ATMrm/U="
  branches:
    - master
    - /^\d/
  deploy_to_forge:
    enabled: true
    tag_regex: "^\\d"
Gemfile:
  required:
    ':system_tests':
      - gem: beaker-hostgenerator
      - gem: "puppet-module-posix-system-r#{minor_version}"
  optional:
    ':development':
      - gem: 'github_changelog_generator'
Rakefile:
  changelog_version_tag_pattern: '%s'
