---
os: linux
dist: xenial
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - "# Update system gems if requested. This is useful to temporarily workaround troubles in the test runner"
  - "# See https://github.com/puppetlabs/pdk-templates/commit/705154d5c437796b821691b707156e1b056d244f for an example of how this was used"
  - "# Ignore exit code of SIGPIPE'd yes to not fail with shell's pipefail set"
  - '[ -z "$RUBYGEMS_VERSION" ] || (yes || true) | gem update --system $RUBYGEMS_VERSION'
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.7
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^\d
    name: deploy
jobs:
  fast_finish: true
  include:
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.7
      stage: spec
    -
      bundler_args: 
      env: ["PUPPET_INSTALL_TYPE=agent", "BEAKER_IS_PE=no", "BEAKER_PUPPET_COLLECTION=puppet5", "BEAKER_debug=true", "BEAKER_setfile=debian8-64{hypervisor=docker}"]
      rvm: default
      script: bundle exec rspec spec/acceptance/*_spec.rb
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: 
      env: ["PUPPET_INSTALL_TYPE=agent", "BEAKER_IS_PE=no", "BEAKER_PUPPET_COLLECTION=puppet5", "BEAKER_debug=true", "BEAKER_setfile=debian9-64{hypervisor=docker}"]
      rvm: default
      script: bundle exec rspec spec/acceptance/*_spec.rb
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: 
      env: ["PUPPET_INSTALL_TYPE=agent", "BEAKER_IS_PE=no", "BEAKER_PUPPET_COLLECTION=puppet5", "BEAKER_debug=true", "BEAKER_setfile=ubuntu1404-64{hypervisor=docker}"]
      rvm: default
      script: bundle exec rspec spec/acceptance/*_spec.rb
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: 
      env: ["PUPPET_INSTALL_TYPE=agent", "BEAKER_IS_PE=no", "BEAKER_PUPPET_COLLECTION=puppet5", "BEAKER_debug=true", "BEAKER_setfile=ubuntu1604-64{hypervisor=docker}"]
      rvm: default
      script: bundle exec rspec spec/acceptance/*_spec.rb
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: 
      env: ["PUPPET_INSTALL_TYPE=agent", "BEAKER_IS_PE=no", "BEAKER_PUPPET_COLLECTION=puppet5", "BEAKER_debug=true", "BEAKER_setfile=ubuntu1804-64{hypervisor=docker}"]
      rvm: default
      script: bundle exec rspec spec/acceptance/*_spec.rb
      services: docker
      sudo: required
    -
      bundler_args: 
      env: ["PUPPET_INSTALL_TYPE=agent", "BEAKER_IS_PE=no", "BEAKER_PUPPET_COLLECTION=puppet5", "BEAKER_debug=true", "BEAKER_setfile=centos6-64{hypervisor=docker}"]
      rvm: default
      script: bundle exec rspec spec/acceptance/*_spec.rb
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: 
      env: ["PUPPET_INSTALL_TYPE=agent", "BEAKER_IS_PE=no", "BEAKER_PUPPET_COLLECTION=puppet5", "BEAKER_debug=true", "BEAKER_setfile=centos7-64{hypervisor=docker}"]
      rvm: default
      script: bundle exec rspec spec/acceptance/*_spec.rb
      services: docker
      stage: acceptance
      sudo: required
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
branches:
  only:
    - master
    - /^v\d/
    - /^\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  username: camptocamp
  password:
    secure: "HLOnMqlB03FRSusdbWf/afjyc0jbHgoVZ/HF4x8y9H7g8utuBQJxjsAAxdrAme5JOuN6i3+J1A8IrpcRIwicBDk/yav4IrT65fCyzfBz7p6Kx2doT4a3WwiMXzqgcDe8Z8l7hu531HnXzxXEjCKCoEFiUBWI+4ULXQk3ATMrm/U="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
