name         'camptocamp-bind'
version      '0.0.1'
source       'https://github.com/camptocamp/puppet-bind'
author       'DevOps Team / Camptocamp'
license      'GNU GPLv3'
summary      'Camptocamp Bind Module'
description  'Bind Module for Puppet'
project_page 'https://github.com/camptocamp/puppet-bind'
