name         'camptocamp-bind'
version      '0.2.1'
source       'https://github.com/camptocamp/puppet-bind'
dependency   'puppetlabs/stdlib', '0.0.1'
dependency   'ripienaar/concat', '0.0.1'
author       'DevOps Team / Camptocamp'
license      'GNU GPLv3'
summary      'Camptocamp Bind Module'
description  'Bind Module for Puppet'
project_page 'https://github.com/camptocamp/puppet-bind'
